package models

const contact = `
	CREATE TABLE IF NOT EXISTS contact (
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		SUBJECT VARCHAR(255) NOT NULL,
		NAME	VARCHAR(60) NOT NULL,
		EMAIL	VARCHAR(255) NOT NULL,
		MEDIA	VARCHAR(255) NULL,
		PHONE	VARCHAR(20) NULL,
		ADDRESS	VARCHAR(255) NULL,
		SET_MODE	ENUM('godev', 'chemenger'),
		CREATED_AT	TIME NULL
	)
`

const user = `
	CREATE TABLE IF NOT EXISTS user (
		MODE ENUM('godev', 'chemenger') PRIMARY KEY,
		CONTACT_ID INT,
		NAME VARCHAR(60) NOT NULL,
		EMAIL VARCHAR(60) NOT NULL,
		FOREIGN KEY (CONTACT_ID) REFERENCES contact(ID)
	)
`

const home = `
	CREATE TABLE IF NOT EXISTS home (
		USER_MODE ENUM('godev', 'chemenger') PRIMARY KEY,
		IMAGE VARCHAR(255) NOT NULL,
		LOGO VARCHAR(255) NOT NULL,
		INFO VARCHAR(255) NOT NULL,
		FOREIGN KEY (USER_MODE) REFERENCES user(MODE)
	)
`

const about = `
	CREATE TABLE IF NOT EXISTS about (
		USER_MODE ENUM('godev', 'chemenger') PRIMARY KEY,
		DETAILS VARCHAR(255) NOT NULL,
		STACKS VARCHAR(255) NOT NULL,
		CV VARCHAR(60) NOT NULL,
		FOREIGN KEY (USER_MODE) REFERENCES user(MODE)
	)
`

const experience = `
	CREATE TABLE IF NOT EXISTS experience (
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		USER_MODE ENUM('godev', 'chemenger'),
		ROLE VARCHAR(255) NOT NULL,
		ORGANIZATION VARCHAR(60) NOT NULL,
		START TIME NULL,
		END TIME NULL,
		FOREIGN KEY (USER_MODE) REFERENCES user(MODE)
	)
`

const review = `
	CREATE TABLE IF NOT EXISTS review (
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		USER_MODE ENUM('godev', 'chemenger'),
		NAME VARCHAR(60) NULL,
		DETAIL VARCHAR(255) NULL,
		PHONE VARCHAR(20) NULL,
		EMAIL VARCHAR(60) NULL,
		FOREIGN KEY (USER_MODE) REFERENCES user(MODE)
	)
`

const services = `
	CREATE TABLE IF NOT EXISTS services (
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		USER_MODE ENUM('godev', 'chemenger'),
		ICON_URL VARCHAR(60) NOT NULL,
		NAME VARCHAR(60) NOT NULL,
		FOREIGN KEY (USER_MODE) REFERENCES user(MODE)
	)
`

const project = `
	CREATE TABLE IF NOT EXISTS project (
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		USER_MODE ENUM('godev', 'chemenger'),
		IMAGE VARCHAR(60) NOT NULL,
		GITHUB_URL VARCHAR(60) NULL,
		DEPLOY_URL VARCHAR(60) NULL,
		NAME VARCHAR(60) NOT NULL,
		DETAIL VARCHAR(255) NOT NULL,
		STACKS VARCHAR(255) NOT NULL,
		COMMENT VARCHAR(255) NULL,
		LIKES INT NULL,
		FOREIGN KEY (USER_MODE) REFERENCES user(MODE)
	)
`
